networks:
  default:
    name: nerd-api-network
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  pg:
    container_name: db-nerd
    image: postgres:12
    restart: always
    ports:
      - "10018:5432"
    mem_limit: 200M
    environment:
      - POSTGRES_USER=nerd
      - POSTGRES_PASSWORD=BS8MJL4s0H5xi2VOSoqT0cMrEy6Ils
      - POSTGRES_DB=nerd
